export default [
  {
    id: "pj-1",
    bg: "/images/GoFreight/banner.jpg",
    role: ["Wireframing", "UI Design", "Visual Design", "Illustration"],
    platforms: "Internet",
    years: "2022",
    subtitle: "〔 Website 〕",
    title: ["GoFreight", "Website"],
  },
  {
    id: "pj-2",
    bg: "/images/GoFreight/banner.jpg",
    role: ["Illustration", "Animation", "Visual Design"],
    platforms: "Facebook, Youtube",
    years: "2022",
    subtitle: "〔 Social Media 〕",
    title: ["GoFreight", "Social Media"],
  },
  {
    id: "pj-3",
    bg: "/images/GoFreight/banner.jpg",
    role: [
      "Wireframing",
      "Screen Flows",
      "Visual Design",
      "Interaction Design",
    ],
    platforms: "iOS, Android",
    years: "2021-2022",
    subtitle: "〔 APP 〕",
    title: ["WorkFe", "工作咖啡"],
  },
  {
    id: "pj-4",
    bg: "/images/GoFreight/banner.jpg",
    role: [
      "Illustration",
      "Wireframing",
      "Screen Flows",
      "Visual Design",
      "Interaction Design",
    ],
    platforms: "Not Release",
    years: "2021-2022",
    subtitle: "〔 APP 〕",
    title: ["Foodie Snail", "吃貨蝸牛"],
  },
  {
    id: "pj-5",
    bg: "/images/ease/banner.jpg",
    role: ["Wireframing", "UI Design", "User Flow", "Interaction Design"],
    platforms: "Saas",
    years: "2021-2022",
    subtitle: "〔 Saas Software 〕",
    title: ["HPAEHM", "長者健康", "管理平台"],
  },
  {
    id: "pj-6",
    bg: "/images/ease/banner.jpg",
    role: ["Wireframing", "UI Design", "Interaction Design"],
    platforms: "Saas",
    years: "2021",
    subtitle: "〔 Saas Software 〕",
    title: ["ease", "地理資訊平台"],
  },
];
